/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bupt_edu_dctblock_JniUtils */

#ifndef _Included_bupt_edu_dctblock_JniUtils
#define _Included_bupt_edu_dctblock_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bupt_edu_dctblock_JniUtils
 * Method:    rectifyImg
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_bupt_edu_dctblock_JniUtils_siftRec
  (JNIEnv *,jclass,jlong,jlong,jint);

#ifdef __cplusplus
}
#endif
#endif
